version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

defaults: &defaults
  docker:
    - image: cimg/node:18.17

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: npm run lint
      - run: npm run lint:lockfile
      - run: npm run test
      - run: npm run build

  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: cp .npmrc-ci .npmrc
      - run: npm install
      - run: npm run build
      - run: npm publish --access public

workflows:
  version: 2
  all:
    jobs:
      - install:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
          post-steps:
            - codecov/upload:
                file: ./coverage/lcov.info
                flags: unit-tests
      - release:
          requires:
            - install
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
